name: cd-cd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/pemt7511/public_html/
            git clone https://github.com/asnur/pemira-project -b master
            cd sip-dev-laravel
            git pull origin master
            composer install
